myblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    #path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>',
        views.post_list, name='post_detail_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('search', views.search, name='search'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

""" Dodanie ścierzki do obrazów """
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    CATEGORY =(
        ('film', 'Film'),
        ('books', 'Książki'),
        ('tochnologies', 'Technologie'),
        ('another', 'Inne'),
    )
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length = 250, unique_for_date='publish') #krutka etykieta do tworzenia opisów dla SEO
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    category = models.CharField(max_length = 12, choices = CATEGORY, default = 'another')
    status = models.CharField(max_length = 10, choices = STATUS_CHOICES, default = 'draft')
    image = models.ImageField(null=True, blank=True) # pole do pobierania obrazu

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    object = models.Manager()
    published = PublishedManager()

    # Metoda wykorzystywana do tworzenia łączy do poszczegulnych postów
    def get_absolute_url(self):
         return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, 
                             self.slug
                             ])

    tags = TaggableManager()

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Metta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

class AboutAuthor(models.Model):
    name = models.CharField(max_length=80)
    description = models.TextField()

    def __str__(self):
        return 'Opis dodany'

class Contact(models.Model):
    title = models.CharField(max_length=80)
    telephone_number = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return 'Dane kontaktowe dodane'

myblog/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length = 25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    """Dodawanie znaczników butsrapa(css) do generowangeo kodu formularza przez django"""
    def __init__(self, *args, **kwargs):
        super(EmailPostForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['to'].widget.attrs.update({'class': 'form-control'})
        self.fields['comments'].widget.attrs.update({'class': 'form-control'})

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'name', 'email', 'body'}

    """Dodawanie znaczników butsrapa(css) do generowangeo kodu formularza przez django"""
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['body'].widget.attrs.update({'class': 'form-control'})

class SearchForm(forms.Form):
    search = forms.CharField(max_length = 50)

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, AboutAuthor, Contact, Comment
from django.core.paginator import Paginator, EmptyPage,  PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

from .forms import EmailPostForm, CommentForm, SearchForm

def post_list(request):
    posts = Post.published.all()
    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    return render(request, 'blog/post/list.html', {'posts': posts, 'tags_list': tags_list, 'posts_activity_list': posts_activity_list})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug = post,
                                   status = 'published',
                                   publish__year = year,
                                   publish__month = month,
                                   publish__day = day)

    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów

    #Lista aktywnych komentarzy dla danego posta
    comments = post.comments.filter(active=True)
    if request.method == "POST":
        #komentarz został opublikowany
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #Utworzenie obiektu comment
            new_comment = comment_form.save(commit=False)
            #Przypisanie komentarza do bierzącego posta
            new_comment.post = post
            #Zapisanie komentarza w bazie danych
            new_comment.save()
    else:
        comment_form = CommentForm()

    """Obsługa proponowania pdobnych postów za pomocą tagó"""
    post_tag_ids = post.tags.values_list('id', flat=True)#flat=True powoduje wyświetleni listyw ppstaci [1,2,3]
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id = post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post' : post,
                                                     'comments' : comments,
                                                     'comment_form' : comment_form,
                                                     'similar_posts' : similar_posts,
                                                     'tags_list': tags_list,
                                                     'posts_activity_list' : posts_activity_list})


def post_list(request, tag_slug=None):
    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    object_list = Post.published.all()
    tag = None


    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags_in=[tag])

    paginator = Paginator(object_list, 3) # Trzy posty na każdej stronie
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #Jeśli zmienna page nie jest zmienną całkowitą
        # Wtedy pobierana jest pierwsza strona wyników
        posts = paginator.page(1)
    except EmptyPage:
        #Jeśli zmienna page ma nómer więkrzy niż numer ostatniej strony
        #Pobierana zostanie ostatnia strona wyników
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',{'page':page, 'posts':posts, 'tag':tag, 'tags_list': tags_list, 'posts_activity_list': posts_activity_list })

#obsułga formularza pozwalającego na wysyłanie postu emailem
def post_share(request, post_id):
    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    # Pobierz post wg id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Formularz przesłano
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Pola formualarza zostały pomyślnie zwalidowane
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} poleca, żebyś przeczytał {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"Komentarzy {cd['name']}: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True


    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent,
                                                    'tags_list':tags_list,
                                                    'posts_activity_list':posts_activity_list})

def about(request):
    """Obsługa widoku o autorze"""
    about = AboutAuthor.objects.all()
    posts = Post.published.all()
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    tags_list = getTag() #lista tagów do wyświetlenia

    return render(request, 'blog/about.html', {'about': about, 'posts': posts, 'tags_list': tags_list, 'posts_activity_list': posts_activity_list})

def contact(request):
    """Obsługa widoku kontakt"""
    contacts = Contact.objects.all()
    posts = Post.published.all()
    posts_activity_list = getActivity() # Wyświtalnie listy ostanio dodanych postów
    tags_list = getTag()  # lista tagów do wyświetlenia
    return render(request, 'blog/contact.html', {'contacts': contacts, 'posts': posts, 'tags_list':tags_list, 'posts_activity_list': posts_activity_list})

def search(request):
    """Obsługa widoku wyszukiwarki artykłów"""
    form = SearchForm(request.POST)
    posts =None
    if request.method == 'POST':
        if form.is_valid():
            #formularz został wysłany pomyślnie
            object_list = Post.published.all()
            cd = form.cleaned_data
            try:
                post_by_title =  get_object_or_404(Post, title=cd['search'])
                posts = object_list.filter(title=post_by_title)
            except :
              print("Nie znalezione Artykułów")
    else:
        form = SearchForm()
        posts = None


    return render(request, 'blog/search.html ', {'form':form, 'posts':posts })

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

"""Metoda przygotowój ąca listę tagów do wyświtlenia """
def getTag():
    tags = Post.tags.all()
    return tags

"""Pobranie trzech ostatnich aktywności(oastanich trzech doadnych postów"""
def getActivity():
   posts_list =Post.published.all()
   posts_list = posts_list.filter().order_by('-publish')[0:3]
   return posts_list

myblog/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="container">
    <div class="mt-4 p-5 bg-light rounded">
        <h1>{{ post.title }}</h1>
        {% if post.image %}
            <img src="{{ post.image.url }}">
        {% endif %}
        <p class="date">
            Opublikowany {{ post.publish }} przez {{ post.author }}
        </p>
        {{ post.body|linebreaks }}

        <a href="{% url "blog:post_share" post.id %}" class="btn btn-primary">
        Udostepnij
        </a>
        <div class="mt-4 p-5 bg-warning rounded">
        {% with comments.count as total_comments %}
            <h3>
                {{total_comments}} komentarz {{ total_comments|pluralize:"y" }}
            </h3>
            <h3>Komentarze :</h3>
                {% for comment in comments%}
                    <div class="mt-4 p-5 bg-info rounded">
                        <p>
                            Komentarz {{forloop.counter}} dodany przez {{comment.name}}
                            {{comment.created}}
                        </p>
                        {{comment.body|linebreaks}}
                    </div>
                {% empty %}
                    <div class="mt-4 p-5 bg-info rounded">
                        Nie ma jeszcze żadnych komentarzy
                    </div>
                {% endfor %}

            <!-- Dodawanie nowgo koentarzas -->
            {% if new_comment %}
                <h3>Twój komentarz został dodany</h3>
            {% else %}
             <h3>Dodaj nowy komentarz</h3>
            <form action="." method="post">
                <div class="mb-3 mt-3 ">
                    {{comment_form.as_p}}
                    {% csrf_token %}
                </div>
                <input type="submit" value="Dodaj komentarz"class="btn btn-primary">
             </form>
            {% endif %}
        </div>
        {% endwith %}
    </div>
    <div class="mt-4 p-5 bg-light rounded">
    <h3>Podobne posty : </h3>
    {% for post in similar_posts %}
        <ul>
            <li>
                 <a href="{{ post.get_absolute_url}}">{{post.title}}</a>
            </li>
        </ul>
    {% empty %}
        <p>Brak podobnych postó</p>
    {% endfor %}
    </div>
</div>

{% endblock %}

myblog/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Mój Blog{% endblock %}

{% block content %}
<div class="container">
  {% for post in posts %}
    <div class="mt-4 p-5 bg-light rounded">
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Opublikowany: {{ post.publish }} przez {{ post.author }}, Kategoria: {{post.category}}
    </p>
    <p class="tags">
      Tagi: {{post.tags.all|join:", "}}
    </p>
   {{ post.body|truncatewords:30|linebreaks }}
    </div>
  {% endfor %}
</div>



{% include "pagination.html" with page=page_obj %}
{% endblock %}

myblog/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij post{% endblock %}

{% block content %}
  <div class="container">
    <div class="mt-4 p-5 bg-light rounded">
      {% if sent %}
        <h3>E-mail pomyślnie wysłano</h3>
        <p>
          "{{ post.title }}" pomyślnie wysłano do {{ form.cleaned_data.to }}.
        </p>
      {% else %}
      <h3>Udostępnij "{{ post.title }}" przez e-mail :</h3>
    <form method="post">
      <div class="mb-3 mt-3 ">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Udostępnij" class="btn btn-primary">
      </div>
    </form>
  {% endif %}
    </div>
  </div>
{% endblock %}