myblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    #path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>',
        views.post_list, name='post_detail_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('search', views.search, name='search'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

""" Dodanie ścierzki do obrazów """
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    CATEGORY =(
        ('film', 'Film'),
        ('books', 'Książki'),
        ('tochnologies', 'Technologie'),
        ('another', 'Inne'),
    )
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length = 250, unique_for_date='publish') #krutka etykieta do tworzenia opisów dla SEO
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    category = models.CharField(max_length = 12, choices = CATEGORY, default = 'another')
    status = models.CharField(max_length = 10, choices = STATUS_CHOICES, default = 'draft')
    image = models.ImageField(null=True, blank=True) # pole do pobierania obrazu

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    object = models.Manager()
    published = PublishedManager()

    # Metoda wykorzystywana do tworzenia łączy do poszczegulnych postów
    def get_absolute_url(self):
         return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, 
                             self.slug
                             ])

    tags = TaggableManager()

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Metta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

class AboutAuthor(models.Model):
    name = models.CharField(max_length=80)
    description = models.TextField()

    def __str__(self):
        return 'Opis dodany'

class Contact(models.Model):
    title = models.CharField(max_length=80)
    telephone_number = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return 'Dane kontaktowe dodane'

myblog/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length = 25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    """Dodawanie znaczników butsrapa(css) do generowangeo kodu formularza przez django"""
    def __init__(self, *args, **kwargs):
        super(EmailPostForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['to'].widget.attrs.update({'class': 'form-control'})
        self.fields['comments'].widget.attrs.update({'class': 'form-control'})

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'name', 'email', 'body'}

    """Dodawanie znaczników butsrapa(css) do generowangeo kodu formularza przez django"""
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['body'].widget.attrs.update({'class': 'form-control'})

class SearchForm(forms.Form):
    search = forms.CharField(max_length = 50)

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, AboutAuthor, Contact, Comment
from django.core.paginator import Paginator, EmptyPage,  PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

from .forms import EmailPostForm, CommentForm, SearchForm

def post_list(request):
    posts = Post.published.all()
    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    return render(request, 'blog/post/list.html', {'posts': posts, 'tags_list': tags_list, 'posts_activity_list': posts_activity_list})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug = post,
                                   status = 'published',
                                   publish__year = year,
                                   publish__month = month,
                                   publish__day = day)

    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów

    #Lista aktywnych komentarzy dla danego posta
    comments = post.comments.filter(active=True)
    if request.method == "POST":
        #komentarz został opublikowany
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #Utworzenie obiektu comment
            new_comment = comment_form.save(commit=False)
            #Przypisanie komentarza do bierzącego posta
            new_comment.post = post
            #Zapisanie komentarza w bazie danych
            new_comment.save()
    else:
        comment_form = CommentForm()

    """Obsługa proponowania pdobnych postów za pomocą tagó"""
    post_tag_ids = post.tags.values_list('id', flat=True)#flat=True powoduje wyświetleni listyw ppstaci [1,2,3]
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id = post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post' : post,
                                                     'comments' : comments,
                                                     'comment_form' : comment_form,
                                                     'similar_posts' : similar_posts,
                                                     'tags_list': tags_list,
                                                     'posts_activity_list' : posts_activity_list})


def post_list(request, tag_slug=None):
    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    object_list = Post.published.all()
    tag = None


    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags_in=[tag])

    paginator = Paginator(object_list, 3) # Trzy posty na każdej stronie
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #Jeśli zmienna page nie jest zmienną całkowitą
        # Wtedy pobierana jest pierwsza strona wyników
        posts = paginator.page(1)
    except EmptyPage:
        #Jeśli zmienna page ma nómer więkrzy niż numer ostatniej strony
        #Pobierana zostanie ostatnia strona wyników
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',{'page':page, 'posts':posts, 'tag':tag, 'tags_list': tags_list, 'posts_activity_list': posts_activity_list })

#obsułga formularza pozwalającego na wysyłanie postu emailem
def post_share(request, post_id):
    tags_list = getTag()  # lista tagów do wyświetlenia
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    # Pobierz post wg id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Formularz przesłano
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Pola formualarza zostały pomyślnie zwalidowane
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} poleca, żebyś przeczytał {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"Komentarzy {cd['name']}: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True


    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent,
                                                    'tags_list':tags_list,
                                                    'posts_activity_list':posts_activity_list})

def about(request):
    """Obsługa widoku o autorze"""
    about = AboutAuthor.objects.all()
    posts = Post.published.all()
    posts_activity_list = getActivity()  # Wyświtalnie listy ostanio dodanych postów
    tags_list = getTag() #lista tagów do wyświetlenia

    return render(request, 'blog/about.html', {'about': about, 'posts': posts, 'tags_list': tags_list, 'posts_activity_list': posts_activity_list})

def contact(request):
    """Obsługa widoku kontakt"""
    contacts = Contact.objects.all()
    posts = Post.published.all()
    posts_activity_list = getActivity() # Wyświtalnie listy ostanio dodanych postów
    tags_list = getTag()  # lista tagów do wyświetlenia
    return render(request, 'blog/contact.html', {'contacts': contacts, 'posts': posts, 'tags_list':tags_list, 'posts_activity_list': posts_activity_list})

def search(request):
    """Obsługa widoku wyszukiwarki artykłów"""
    form = SearchForm(request.POST)
    posts =None
    if request.method == 'POST':
        if form.is_valid():
            #formularz został wysłany pomyślnie
            object_list = Post.published.all()
            cd = form.cleaned_data
            try:
                post_by_title =  get_object_or_404(Post, title=cd['search'])
                posts = object_list.filter(title=post_by_title)
            except :
              print("Nie znalezione Artykułów")
    else:
        form = SearchForm()
        posts = None


    return render(request, 'blog/search.html ', {'form':form, 'posts':posts })

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

"""Metoda przygotowój ąca listę tagów do wyświtlenia """
def getTag():
    tags = Post.tags.all()
    return tags

"""Pobranie trzech ostatnich aktywności(oastanich trzech doadnych postów"""
def getActivity():
   posts_list =Post.published.all()
   posts_list = posts_list.filter().order_by('-publish')[0:3]
   return posts_list

myblog/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}O autorze{% endblock %}

{% block content %}
<div class="container">
    <div class="mt-4 p-5 bg-light rounded">
    {% for ab in about %}
    <div class="authorPhoto">
        <img src="{% static 'img/avatarAuthor.png' %}"/>
    </div>
    <h2>
       {{ ab.name }}

    </h2>
     <p >
      {{ ab.description }}
    </p>

    {% endfor %}
        </div>
</div>
{% endblock %}

myblog/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- Bootsrap from cdn -->
        <!-- Latest compiled and minified CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Latest compiled JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <!-- menu -->
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:post_list' %}">MyBlog.com</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="mynavbar">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:post_list' %}">Strona glówna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:about' %}">O Autorze</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:contact' %}">Kontakt</a>
                        </li>
                    </ul>
                    <!-- Wyszukiwarka -->>
                    <form class="d-flex">
                        <input class="form-control me-2" type="text" placeholder="Search">
                        <button class="btn btn-primary" type="button">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Page Header -->
        <header class="masthead p-5 " style="background-image: url(/static/img/home-bg.jpg)">
            <div class="col-lg-2 mx-auto">
                <div class="site-heading">
                    <h1>Mój blog</h1>
                        <span class="subheading">To jest blog o wszystkim</span>
                </div>
            </div>
        </header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-8 p-3">
                    {% block content %}
                    {% endblock %}
                </div>
                <div class="col-sm-4 p-3 ">
                    <div class="container">
                        <div class="mt-4 p-5 bg-light rounded">
                            <h4> Tagi :</h4>
                                {% for tag in tags_list %}
                                    <ul>
                                        <li>
                                            {{ tag }}
                                        </li>
                                    </ul>
                                {% endfor %}
                        </div>
                         <div class="mt-4 p-5 bg-light rounded">
                            <h4> Ostatnio dodane posty:</h4>
                             {% for post_activ in posts_activity_list %}
                                    <ul>
                                        <li>
                                            <a href="{{ post_activ.get_absolute_url }}">
                                                 {{ post_activ.title }}
                                            </a> | {{ post_activ.publish }}
                                        </li>
                                    </ul>
                                {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <footer class="text-center">

        <p class="copyright text-muted">Copyright &copy; Your Website 2023</p>
    </footer>


</html>

myblog/blog/templates/blog/contact.html
{% extends "blog/base.html" %}

{% block title %}Kontakt{% endblock %}

{% block content %}
    <div class="container">
        <div class="mt-4 p-5 bg-light rounded">
            {% for contact in contacts %}
                {{ contact.title }}<br>
                Numer Telefonu : {{ contact.telephone_number }}<br>
                Email : {{ contact.email }}
            {% endfor%}
        </div>
    </div>
{% endblock %}

myblog/blog/templates/blog/search.html
{% extends "blog/base.html" %}

{% block title %}Wyszukiwarka{% endblock %}

{% block content %}
    <div class="comment">
        <h2>
            Znalezione artykuły :
        </h2>
        {% for post in posts%}
        <h4>
            <div class="comment">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
            </div>
        </h4>
    </div>
    {% empty %}
        <p>Nie znaleziono żadnego artykułu</p>
    {% endfor %}
</div>

    <h2>Wyszukaj artykół : </h2>
  <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
       <p><input type="submit" value="Szukaj"></p>
  </form>

{% endblock %}